---
- hosts: all
  become: true
  vars:
    created_username: alex

  tasks:

    - name: Sleep for 20 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 20

    - name: Update repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - virtualenv
        state: latest

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install containerd
      apt:
        name: containerd.io
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Enable Docker service
      ansible.builtin.command: systemctl enable docker

    - name: Start Docker service
      ansible.builtin.command: systemctl start docker

    - name: Log into DockerHub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Create api.env file
      ansible.builtin.copy:
        dest: api.env
        src: api.env

    - name: Create db.env file
      ansible.builtin.copy: 
        dest: db.env
        src: db.env

    - name: Create docker-compose file
      ansible.builtin.copy:
        dest: docker-compose.yml
        src: docker-compose.yml 

    - name: Run docker compose up
      ansible.builtin.command: docker compose up -d
