name: Docker Build on Push to Development

on:
  push:
    branches:
      - 'development'

permissions: write-all

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_LOGIN_USERNAME }}
          password: ${{ secrets.DH_LOGIN_PASSWORD }}
      
      - name: Build and push FE Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: valenciaga/portfolio_frontend:latest
